import { Activity, BarChart3, Bell, Car, LayoutDashboard, Map, Plug, Shield, Zap } from 'lucide-react'

export const stations = [
  { name: 'Andheri East', city: 'Mumbai', status: 'Available', color: 'green', x: '22%', y: '33%' },
  { name: 'Hinjewadi Phase 2', city: 'Pune', status: 'Available', color: 'green', x: '68%', y: '60%' },
  { name: 'Koramangala', city: 'Bangalore', status: 'Charging', color: 'blue', x: '50%', y: '27%' },
  { name: 'Connaught Place', city: 'Delhi', status: 'Occupied', color: 'red', x: '76%', y: '24%' },
]

export const features = [{ icon: Map, title: 'Real-Time Station Map', copy: 'Live availability across Indian cities. Filter by charger type, speed, and distance. Always know where to charge next.' }, { icon: Activity, title: 'AI Demand Forecasting', copy: 'LSTM-powered predictions per station. Anticipate peak hours before they happen and balance your network proactively.', green: true }, { icon: Zap, title: 'Live Session Monitoring', copy: 'Track power output, state-of-charge, and session duration in real time. Get instant alerts when sessions deviate.' }, { icon: Bell, title: 'Smart Notifications', copy: 'Booking confirmations, congestion warnings, availability alerts — delivered at the right moment to drivers and operators.' }, { icon: BarChart3, title: 'Operator Analytics', copy: 'Revenue trends, usage patterns, and peak-hour insights. Make data-driven decisions about your charging network.' }, { icon: Shield, title: 'Role-Based Access', copy: 'Separate dashboards for EV Drivers, Station Operators, and Platform Admins. The right view for every stakeholder.' }]
export const roles = { Drivers: { icon: Car, badge: 'EV Driver', title: 'Find, Book, Charge', copy: 'Real-time station finder with smart routing, live wait times, and slot booking — built for Indian roads.', bullets: ['Live map with availability filters', 'Estimated wait time per station', 'Route-aware station recommendations', 'OCPP-compatible with all major EVs'] }, Operators: { icon: Plug, badge: 'Station Operator', title: 'Manage & Monetize', copy: 'Full control over your charging stations — monitor performance, track revenue, and respond to congestion alerts in real time.', bullets: ['Real-time station status dashboard', 'Revenue and usage analytics', 'Congestion and fault alerts', 'Multi-station fleet management'] }, Admins: { icon: LayoutDashboard, badge: 'Admin', title: 'Control the Network', copy: 'Platform-wide oversight, user management, system health monitoring, and compliance reporting — all in one place.', bullets: ['User and operator management', 'Network-wide health monitoring', 'AI model performance tracking', 'Audit logs and access control'] } }