'use client'

import Link from 'next/link'
import CountUp from 'react-countup'
import { motion, AnimatePresence } from 'framer-motion'
import { Activity, AlertTriangle, BarChart3, Bell, Building2, CheckCircle2, IndianRupee, LayoutDashboard, LogOut, Map, Menu, Settings, TrendingUp, Wifi, X, XCircle, Zap } from 'lucide-react'
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useState } from 'react'
import { liveSessions, operatorProfile, operatorStations, recentAlerts, revenueByDay } from '@/lib/mock/operator-data'
import './operator.css'

const nav = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Live Sessions', icon: Zap, badge: '4' },
  { label: 'My Stations', icon: Building2 }, { label: 'Analytics', icon: BarChart3 },
  { label: 'Alerts', icon: Bell, badge: '2' }, { label: 'Settings', icon: Settings },
]

function StatCard({ icon: Icon, label, value, suffix = '', prefix = '', trend, tone, live = false }: { icon: typeof Zap; label: string; value: number; suffix?: string; prefix?: string; trend: string; tone: string; live?: boolean }) {
  return <motion.div className="op-stat-card" initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} whileHover={{ y: -3 }}>
    <div className={`op-stat-icon ${tone}`}><Icon size={19} /></div><span className="op-stat-label">{label}</span>
    <strong className={live ? 'live-number' : ''}><CountUp end={value} prefix={prefix} suffix={suffix} duration={2} enableScrollSpy /></strong>
    <small className={trend.includes('+') || live ? 'positive' : ''}>{live && <i className="op-pulse" />}{trend}</small>
  </motion.div>
}

export default function OperatorDashboard() {
  const [active, setActive] = useState('Overview'); const [alertsOpen, setAlertsOpen] = useState(false); const [addOpen, setAddOpen] = useState(false); const [mobileOpen, setMobileOpen] = useState(false)
  const [stationName, setStationName] = useState(''); const [city, setCity] = useState('Pune'); const [points, setPoints] = useState('4')
  const iconFor = (type: string) => type === 'warning' ? AlertTriangle : type === 'info' ? Bell : type === 'success' ? CheckCircle2 : XCircle
  const alertClass = (type: string) => `op-alert ${type}`
  return <div className="operator-shell">
    <aside className="operator-sidebar">
      <div className="operator-logo"><Zap size={20} fill="currentColor" /> EVspark</div><p className="operator-kicker">Operator Dashboard</p>
      <div className="operator-profile"><div className="operator-avatar">A</div><div><b>Aakash Mehta</b><span>GreenCharge Hub</span><small><i /> Verified Operator</small></div></div>
      <nav className="operator-nav"><p>MAIN</p>{nav.map(item => { const Icon = item.icon; return <button key={item.label} className={active === item.label ? 'active' : ''} onClick={() => setActive(item.label)}><Icon size={17} /> {item.label}{item.badge && <em>{item.badge}</em>}</button> })}<p>QUICK LINKS</p><Link href="/dashboard/driver"><Map size={17} /> View Driver Map</Link><Link className="signout" href="/auth/login"><LogOut size={17} /> Sign Out</Link></nav>
      <div className="operator-help">Need help?<b>support@evspark.in</b></div>
    </aside>
    <main className="operator-main">
      <header className="operator-topbar"><button className="operator-mobile-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open menu"><Menu size={20} /></button><div><h1>Good morning, Aakash</h1><p>GreenCharge Hub · Pune</p></div><div className="operator-top-actions"><span>September 6, 2026</span><button className="op-bell" onClick={() => setAlertsOpen(true)} aria-label="Open alerts"><Bell size={19} /><i>2</i></button><button className="add-station" onClick={() => setAddOpen(true)}>Add Station +</button></div></header>
      <div className="operator-mobile-nav">{mobileOpen && <>{nav.slice(0, 5).map(item => <button key={item.label} className={active === item.label ? 'active' : ''} onClick={() => { setActive(item.label); setMobileOpen(false) }}><item.icon size={16} /><span>{item.label.split(' ')[0]}</span></button>)}</>}</div>
      <section className="op-stats"><StatCard icon={IndianRupee} label="Monthly Revenue" value={38400} prefix="₹" trend="+18% vs last month" tone="blue" /><StatCard icon={Activity} label="Sessions This Month" value={264} trend="+24 vs last month" tone="green" /><StatCard icon={Wifi} label="Avg Uptime" value={98.4} suffix="%" trend="All 3 stations reporting" tone="purple" /><StatCard icon={Zap} label="Live Sessions" value={4} trend="Live" tone="amber" live /></section>
      <section className="op-chart-grid"><div className="op-panel op-revenue"><div className="op-panel-head"><div><h2>Sessions &amp; Revenue</h2><span>Last 7 days</span></div><TrendingUp size={17} color="#10B981" /></div><ResponsiveContainer width="100%" height={235}><ComposedChart data={revenueByDay} margin={{ top: 8, right: 4, left: -22, bottom: 0 }}><CartesianGrid stroke="#f1f5f9" strokeDasharray="3 3" /><XAxis dataKey="day" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><YAxis yAxisId="left" tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><YAxis yAxisId="right" orientation="right" tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ border: '0', borderRadius: 12, boxShadow: '0 10px 30px #0f172a18' }} formatter={(value, name) => [name === 'revenue' ? `₹${value}` : value, name === 'revenue' ? 'Revenue' : 'Sessions']} /><Bar yAxisId="left" dataKey="sessions" fill="#2563EB" opacity={.85} radius={[4, 4, 0, 0]} /><Line yAxisId="right" type="monotone" dataKey="revenue" stroke="#10B981" strokeWidth={2.5} dot={false} /></ComposedChart></ResponsiveContainer><div className="op-chart-legend"><span><i className="legend-blue" /> Sessions</span><span><i className="legend-green" /> Revenue</span></div></div><div className="op-panel utilization"><div className="op-panel-head"><div><h2>Charger Utilization</h2><span>Right now</span></div><Activity size={17} color="#64748b" /></div>{operatorStations.map(station => { const percentage = Math.round(station.active / station.points * 100); return <div className="util-row" key={station.id}><div><b>{station.name}</b><span>{station.active}/{station.points} points active</span></div><strong>{percentage}%</strong><div className="util-track"><motion.i initial={{ width: 0 }} whileInView={{ width: `${percentage}%` }} viewport={{ once: true }} className={percentage > 70 ? 'emerald' : percentage >= 40 ? 'blue' : 'amber'} /></div></div> })}<small className="updated"><i className="op-pulse" /> Updated 8 sec ago</small></div></section>
      <section className="op-panel sessions-panel"><div className="op-panel-head"><h2>Live Sessions</h2><span className="live-badge"><i className="op-pulse" /> 4 Active</span></div><div className="session-table-wrap"><table className="session-table"><thead><tr>{['User','Vehicle','Station','Charger','Started','Duration','Power','SoC','Est. Cost','Action'].map(h => <th key={h} className={h === 'Station' || h === 'Vehicle' ? 'mobile-hide' : ''}>{h}</th>)}</tr></thead><tbody>{liveSessions.map((session, index) => <motion.tr key={session.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }}><td><span className="user-cell"><i>{session.user[0]}</i>{session.user}</span></td><td className="mobile-hide">{session.vehicle}</td><td className="mobile-hide">{session.station}</td><td><b className="charger-chip">{session.point}</b></td><td>{session.startTime}</td><td>{session.duration} min</td><td className="power-cell">{session.power} kW</td><td><div className="soc"><i style={{ width: `${session.soc}%` }} /></div><small>{session.soc}%</small></td><td className="cost-cell">₹{session.estimatedCost}</td><td><button className="end-session">End Session</button></td></motion.tr>)}</tbody></table></div></section>
      <section className="op-panel alerts-panel"><div className="op-panel-head"><h2>Recent Alerts</h2><button onClick={() => setAlertsOpen(true)}>Mark all read</button></div>{recentAlerts.map(alert => { const Icon = iconFor(alert.type); return <motion.div className={alertClass(alert.type)} key={alert.id} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}><Icon size={17} /><div><b>{alert.message}</b><span>{alert.station} · {alert.time}</span></div></motion.div> })}</section>
    </main>
    <nav className="operator-bottom-tabs">{nav.slice(0, 5).map(item => <button key={item.label} className={active === item.label ? 'active' : ''} onClick={() => setActive(item.label)}><item.icon size={17} /><span>{item.label.split(' ')[0]}</span></button>)}</nav>
    <AnimatePresence>{alertsOpen && <motion.aside className="operator-drawer" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }}><div className="drawer-head"><h2>Recent Alerts</h2><button onClick={() => setAlertsOpen(false)} aria-label="Close alerts"><X size={18} /></button></div>{recentAlerts.map(alert => { const Icon = iconFor(alert.type); return <div className={alertClass(alert.type)} key={alert.id}><Icon size={17} /><div><b>{alert.message}</b><span>{alert.station} · {alert.time}</span></div></div> })}</motion.aside>}</AnimatePresence>
    <AnimatePresence>{addOpen && <motion.aside className="operator-drawer add-drawer" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }}><div className="drawer-head"><h2>Add New Station</h2><button onClick={() => setAddOpen(false)} aria-label="Close panel"><X size={18} /></button></div><label>Station Name<input value={stationName} onChange={e => setStationName(e.target.value)} placeholder="e.g. Wakad EV Hub" /></label><label>City<select value={city} onChange={e => setCity(e.target.value)}><option>Pune</option><option>Mumbai</option><option>Bengaluru</option></select></label><label>Number of Points<select value={points} onChange={e => setPoints(e.target.value)}><option>2</option><option>4</option><option>6</option><option>8</option></select></label><div className="drawer-actions"><button onClick={() => setAddOpen(false)}>Cancel</button><button onClick={() => setAddOpen(false)}>Save Station</button></div></motion.aside>}</AnimatePresence>
  </div>
}
