'use client'

import { AnimatePresence, motion } from 'framer-motion'
import { Car, Check, CheckCircle2, LayoutDashboard, Plug, ShieldCheck, Zap } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { neonAuth, onboardingStorageKey } from '@/lib/neon-auth'

const roleData = { driver: { label: 'EV Driver', icon: Car, desc: 'Find charging stations near you, book slots in advance, and get AI-powered route recommendations.', bullets: ['Real-time station availability', 'Slot booking and reservations', 'Wait time predictions', 'Route-aware suggestions'] }, operator: { label: 'Station Operator', icon: Plug, desc: 'Manage your charging stations, monitor live sessions, view revenue analytics, and get congestion alerts.', bullets: ['Station management dashboard', 'Live session monitoring', 'Revenue and usage analytics', 'Alert and notification center'] }, admin: { label: 'Platform Admin', icon: LayoutDashboard, desc: 'Full platform oversight — manage users, operators, system health, and compliance reporting across the network.', bullets: ['User and operator management', 'Network-wide health monitoring', 'AI model performance tracking', 'Audit logs and access control'] } }
const cities = ['Mumbai', 'Pune', 'Bangalore', 'Delhi', 'Chennai', 'Hyderabad', 'Other']

type Role = keyof typeof roleData

export default function OnboardingPage() {
  const router = useRouter()
  const [step, setStep] = useState(1)
  const [role, setRole] = useState<Role>('driver')
  const [userId, setUserId] = useState('')
  useEffect(() => { const initial = new URLSearchParams(window.location.search).get('role'); if (initial && initial in roleData) setRole(initial as Role); neonAuth.getSession().then((session) => setUserId(session.data?.user?.id || '')) }, [])
  return <main className="onboarding"><div className="onboard-brand"><b>EV<span>spark</span></b></div><div className="step-progress">{[['Your Role', 1], ['Setup', 2], ["You're Ready", 3]].map(([label, num], index) => <div className="step-item" key={label as string}><div className={`step-circle ${step === num ? 'active' : step > Number(num) ? 'complete' : ''}`}>{step > Number(num) ? <Check size={17} /> : num}</div><span>{label as string}</span>{index < 2 && <i className={step > index + 1 ? 'active' : ''} />}</div>)}</div><AnimatePresence mode="wait"><motion.div key={step} className="onboard-content" initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }} transition={{ duration: .3 }}>{step === 1 ? <RoleStep role={role} setRole={setRole} onContinue={() => setStep(2)} /> : step === 2 ? <SetupStep role={role} onContinue={() => setStep(3)} /> : <SuccessStep role={role} onDashboard={() => { if (userId) localStorage.setItem(onboardingStorageKey(userId), '1'); router.push(`/dashboard/${role}`) }} />}</motion.div></AnimatePresence></main>
}

function RoleStep({ role, setRole, onContinue }: { role: Role; setRole: (role: Role) => void; onContinue: () => void }) { return <><h1>How will you use EVspark?</h1><p className="onboard-subtitle">This helps us set up the right dashboard for you.</p><div className="onboard-role-grid">{(Object.keys(roleData) as Role[]).map((key) => { const item = roleData[key]; const Icon = item.icon; return <motion.button type="button" whileHover={{ y: -4, scale: 1.01 }} className={`onboard-role-card ${role === key ? 'selected' : ''}`} key={key} onClick={() => setRole(key)}>{role === key && <span className="selected-check"><Check size={15} /></span>}<span className={`onboard-role-icon ${key}`}><Icon /></span><h2>{item.label}</h2><p>{item.desc}</p><ul>{item.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul></motion.button> })}</div><button className="auth-submit narrow" type="button" onClick={onContinue}>Continue <span>→</span></button></> }

function SetupStep({ role, onContinue }: { role: Role; onContinue: () => void }) {
  const [values, setValues] = useState<Record<string, string>>({})
  const [error, setError] = useState('')
  const setValue = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }))
  const submit = () => { setError(''); const required = role === 'driver' ? ['name', 'city', 'vehicle', 'charger'] : role === 'operator' ? ['business', 'city', 'points', 'chargers'] : ['organization', 'email', 'reason']; if (required.some((key) => !values[key]?.trim())) return setError('Complete every field before continuing.'); if (role === 'admin' && !/^\S+@\S+\.\S+$/.test(values.email)) return setError('Enter a valid official email.'); onContinue() }
  return <div className="setup-step"><h1>{role === 'driver' ? 'Set up your driver profile' : role === 'operator' ? 'Set up your charging station' : 'Admin verification'}</h1>{role === 'admin' && <div className="admin-info"><ShieldCheck /><div><b>Admin access requires verification</b><p>Platform admin accounts are verified by the EVspark team. Enter your organization details below and we&apos;ll activate your account within 24 hours.</p></div></div>}<div className="setup-fields">{role === 'driver' && <><TextField label="Your Name" placeholder="Rahul Sharma" value={values.name || ''} onChange={(value) => setValue('name', value)} /><SelectField label="City" options={cities} value={values.city || ''} onChange={(value) => setValue('city', value)} /><TextField label="EV Model" placeholder="Tata Nexon EV, Ola S1 Pro..." value={values.vehicle || ''} onChange={(value) => setValue('vehicle', value)} /><Pills label="Preferred Charger Type" items={['AC (Slow)', 'DC Fast', 'Both']} value={values.charger || ''} onChange={(value) => setValue('charger', value)} /></>}{role === 'operator' && <><TextField label="Business / Station Name" placeholder="GreenCharge Hub, Pune Station 1..." value={values.business || ''} onChange={(value) => setValue('business', value)} /><SelectField label="City" options={cities} value={values.city || ''} onChange={(value) => setValue('city', value)} /><SelectField label="Number of charging points" options={['1-5', '6-15', '16-50', '50+']} value={values.points || ''} onChange={(value) => setValue('points', value)} /><Pills label="Charger types available" items={['AC 3.3 kW', 'AC 7.2 kW', 'DC 25 kW', 'DC 60 kW', 'DC 120 kW']} value={values.chargers || ''} onChange={(value) => setValue('chargers', value)} /></>}{role === 'admin' && <><TextField label="Organization name" placeholder="Your company or government body" value={values.organization || ''} onChange={(value) => setValue('organization', value)} /><TextField label="Official email" type="email" placeholder="name@company.com" value={values.email || ''} onChange={(value) => setValue('email', value)} /><label className="auth-field"><span>Reason for admin access</span><textarea rows={3} placeholder="Tell us about your responsibilities..." value={values.reason || ''} onChange={(event) => setValue('reason', event.target.value)} /></label></>}</div>{error && <p className="auth-error" role="alert">{error}</p>}<button className="auth-submit narrow" type="button" onClick={submit}>{role === 'admin' ? 'Submit for Review' : 'Continue'} <span>→</span></button></div>
}
function TextField({ label, placeholder, value, onChange, type = 'text' }: { label: string; placeholder: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="auth-field"><span>{label}</span><input type={type} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} /></label> }
function SelectField({ label, options, value, onChange }: { label: string; options: string[]; value: string; onChange: (value: string) => void }) { return <label className="auth-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="" disabled>Select an option</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
function Pills({ label, items, value, onChange }: { label: string; items: string[]; value: string; onChange: (value: string) => void }) { return <div className="pill-field"><span>{label}</span><div>{items.map((item) => <button type="button" key={item} className={value === item ? 'selected' : ''} onClick={() => onChange(item)}>{item}</button>)}</div></div> }
function SuccessStep({ role, onDashboard }: { role: Role; onDashboard: () => void }) { const copy = { driver: 'Your driver profile is ready. Start finding EV stations near you across India.', operator: 'Your station is registered. Head to your dashboard to go live.', admin: "Your request is submitted. We'll review and activate your account within 24 hours." }; const chips = { driver: ['Live Map', 'Wait Times', 'Alerts'], operator: ['Analytics', 'Live Sessions', 'Alerts'], admin: ['Access Control', 'Network Health', 'AI Monitor'] }; return <div className="success-step"><div className="success-icon"><CheckCircle2 /></div><h1>You&apos;re all set! <span>⚡</span></h1><p>{copy[role]}</p><button className="auth-submit success-button" type="button" onClick={onDashboard}>Go to Dashboard <span>→</span></button><div className="success-chips">{chips[role].map((chip) => <span key={chip}>{chip}</span>)}</div><small>Need help? Contact support@evspark.in</small></div> }
