"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";

export default function RegisterPage() {
  const router = useRouter();
  return <main className="flex min-h-screen items-center justify-center px-6 py-12"><section className="w-full max-w-sm rounded-lg border border-border bg-surface p-7"><Link className="flex items-center justify-center gap-2 font-semibold" href="/"><span className="flex h-8 w-8 items-center justify-center rounded bg-primary text-bg">⚡</span>EV<span className="text-primary">spark</span></Link><h1 className="mt-8 text-center text-xl font-semibold">Create your EVspark account</h1><form className="mt-8 space-y-4" onSubmit={(event) => { event.preventDefault(); router.push("/driver"); }}><label className="block text-sm text-muted">Name<input className="mt-2 h-10 w-full rounded-lg border border-border bg-surface-2 px-3 text-text outline-none focus:border-primary" required /></label><label className="block text-sm text-muted">Role<select className="mt-2 h-10 w-full rounded-lg border border-border bg-surface-2 px-3 text-text outline-none focus:border-primary" defaultValue="driver"><option value="driver">Driver</option><option value="operator">Operator</option></select></label><label className="block text-sm text-muted">Email<input className="mt-2 h-10 w-full rounded-lg border border-border bg-surface-2 px-3 text-text outline-none focus:border-primary" type="email" required /></label><label className="block text-sm text-muted">Password<input className="mt-2 h-10 w-full rounded-lg border border-border bg-surface-2 px-3 text-text outline-none focus:border-primary" type="password" required /></label><Button className="w-full" size="lg">Create account</Button></form><p className="mt-7 text-center text-sm text-muted">Already registered? <Link className="text-primary hover:text-text" href="/login">Sign in</Link></p></section></main>;
}