import type { EVStation } from "@/types/station";

export const SEED_STATIONS: Omit<EVStation, "distanceKm" | "etaMinutes">[] = [
  { id: "stn-001", name: "Tata Power EZ Charge - Viviana Mall", address: "Viviana Mall, Pokhran Rd No. 2, Thane West, 400601", lat: 19.2497, lng: 72.9961, status: "available", pricePerKwh: 18, powerKw: 50, connectorType: "CCS2", availableSlots: 3, totalSlots: 4, amenities: ["WiFi", "Food Court", "Parking"], rating: 4.5, network: "Tata Power EZ Charge" },
  { id: "stn-002", name: "Tata Power EZ Charge - Korum Mall", address: "Korum Mall, Eastern Express Hwy, Thane East, 400601", lat: 19.1957, lng: 72.9651, status: "busy", pricePerKwh: 18, powerKw: 50, connectorType: "CCS2", availableSlots: 0, totalSlots: 2, amenities: ["WiFi", "Restroom", "Food Court"], rating: 4.2, network: "Tata Power EZ Charge" },
  { id: "stn-003", name: "ChargeZone - Thane Station Parking", address: "Thane Railway Station Parking, Thane West, 400602", lat: 19.1868, lng: 72.9711, status: "available", pricePerKwh: 15, powerKw: 25, connectorType: "Type 2", availableSlots: 2, totalSlots: 3, amenities: ["Restroom"], rating: 3.8, network: "ChargeZone" },
  { id: "stn-004", name: "Ather Grid - Hiranandani Estate", address: "Hiranandani Estate, Ghodbunder Rd, Thane, 400607", lat: 19.2668, lng: 72.9891, status: "available", pricePerKwh: 20, powerKw: 22, connectorType: "Type 2", availableSlots: 4, totalSlots: 4, amenities: ["WiFi", "Coffee Shop"], rating: 4.7, network: "Ather Grid" },
  { id: "stn-005", name: "HPCL EV Charging - Ghodbunder Road", address: "HPCL Petrol Pump, Ghodbunder Rd, Thane, 400610", lat: 19.254, lng: 72.968, status: "available", pricePerKwh: 14, powerKw: 30, connectorType: "CCS2", availableSlots: 1, totalSlots: 2, amenities: ["Restroom"], rating: 3.9, network: "HPCL" },
  { id: "stn-006", name: "Jio-bp Pulse - Majiwada Junction", address: "Majiwada, Ghodbunder Rd, Thane, 400601", lat: 19.228, lng: 72.974, status: "offline", pricePerKwh: 17, powerKw: 50, connectorType: "CCS2", availableSlots: 0, totalSlots: 2, amenities: ["WiFi", "Coffee Shop", "Restroom"], rating: 4.1, network: "Jio-bp Pulse" },
  { id: "stn-007", name: "ChargeZone - R-City Mall Ghatkopar", address: "R-City Mall, LBS Marg, Ghatkopar West, 400086", lat: 19.0883, lng: 72.9083, status: "available", pricePerKwh: 16, powerKw: 50, connectorType: "CCS2", availableSlots: 3, totalSlots: 4, amenities: ["Food Court", "Parking", "Restroom"], rating: 4.3, network: "ChargeZone" },
  { id: "stn-008", name: "Tata Power EZ Charge - Mulund Check Naka", address: "LBS Road, Mulund West, Mumbai, 400080", lat: 19.1726, lng: 72.9586, status: "busy", pricePerKwh: 18, powerKw: 60, connectorType: "CCS2", availableSlots: 0, totalSlots: 3, amenities: ["WiFi", "Restroom"], rating: 4, network: "Tata Power EZ Charge" },
  { id: "stn-009", name: "Ather Grid - Kalyan Shoppingzone", address: "Shoppingzone Mall, Kalyan West, 421301", lat: 19.2437, lng: 73.1355, status: "available", pricePerKwh: 19, powerKw: 22, connectorType: "Type 2", availableSlots: 2, totalSlots: 2, amenities: ["WiFi", "Food Court"], rating: 4.4, network: "Ather Grid" },
  { id: "stn-010", name: "BPCL EV Charge - Navi Mumbai APMC", address: "APMC Market, Vashi, Navi Mumbai, 400703", lat: 19.076, lng: 73.007, status: "available", pricePerKwh: 15, powerKw: 25, connectorType: "Type 2", availableSlots: 1, totalSlots: 2, amenities: ["Restroom"], rating: 3.6, network: "BPCL" },
  { id: "stn-011", name: "ChargeZone - Dombivli East Depot", address: "Railway Rd, Dombivli East, 421201", lat: 19.2141, lng: 73.0862, status: "available", pricePerKwh: 13, powerKw: 22, connectorType: "Type 2", availableSlots: 3, totalSlots: 4, amenities: ["Restroom"], rating: 3.7, network: "ChargeZone" },
  { id: "stn-012", name: "Tata Power EZ Charge - Bhiwandi Logistic Park", address: "MIDC Industrial Area, Bhiwandi, 421302", lat: 19.3003, lng: 73.0585, status: "available", pricePerKwh: 16, powerKw: 60, connectorType: "CCS2", availableSlots: 5, totalSlots: 6, amenities: ["Restroom", "Parking"], rating: 4.2, network: "Tata Power EZ Charge" },
];